### ISSUE TITLE
How to subscribe to the mailing list

### ISSUE THREAD

**Issue by rob-luke** [fNIRS/snirf#38]
I just attempted to sign up to the mailing list by following the link in the README to https://fnirs.org/resources/software/snirf/ and sending an email to the subscription address snirf-subscribe@fnirs.org. However, this email was unable to be delivered with the error `snirf-subscribe wasn't found at fnirs.org`.

Does the mailing list still exist? If so, is it down? Or have I misunderstood the instructions on the website?

**Comment by fangq** [comment]
@jayd1860 and @dboas, is this mailing list still active? I am getting the same error as @rob-luke when I tested it earlier

```
Address not found
--
Your message wasn't delivered to snirf-unsubscribe@fnirs.org because the address couldn't be found, or is unable to receive mail.
```

**Comment by dboas** [comment]
I think that mailing list died when the SfNIRS web provider tanked and we went with a new service provider that somehow didn’t support mail lists. This was basically because of all the new requirements making mail list compliant with different government requirements. As a result, we migrated our mailing lists to mailchimp.

You can now sign up at
https://mailchi.mp/89a906ec22cf/snirf

However, most updates will be communicated directly through github.

I updated the website. Thanks for bringing that to my attention.

David

**Comment by rob-luke** [comment]
Thanks for getting back to me so quickly. I follow the github page, so that should suffice.

Appreciate the great documentation here. Thanks
