### ISSUE TITLE
nirs(i).probe compatibility with nirs.SD probe definition

### ISSUE THREAD

**Issue by morrisvanegas** [fNIRS/snirf#57]
Is there a reason why snirf(i).probe does not simply carry over the .SD probe structure used previously by .nirs? 

While I understand the addition of fields to support fluorescence (wavelengthEmission), frequency domain (frequencies), and time domain (timeDelays, timeDelayWidths, momentOrders) data types, it seems some important fields were lost.  Some field names, while they changed from SD to snirf(i).probe, are easily converted (SD.SrcPos became snirf(i).sourcePos2D, SD.Lambda became snirf(i).wavelengths).

However, it is unclear how **DummyPos, SpringList, and AnchorList** are translated from .SD to snirf. These three fields allow the translation of a 2D probe onto a 3D model. In particular, modular fNIRS designs heavily leverage DummyPos, SpringList, and AnchorList to maintain rigid distances between optodes on the same module (intra-module channels), and allow for flexibility between optodes on different modules (inter-module channels), when registering a probe to a 3D head model. 

For example (https://github.com/cotilab/moca#3d-export):
A modular probe designed in 2D
![demo_SD_channels](https://user-images.githubusercontent.com/6857168/127538735-a206dcb8-f715-4b5e-b0b5-09acc5cdd78d.png)

Maintains it's modular architecture through extensive optode relationships (inter vs intra module springs). These spring relationships ensure modules (fixed circuit boards) don't stretch--only distances between modules can be adjusted.
![SDgui](https://user-images.githubusercontent.com/6857168/127538905-2d0c2c91-f67d-41b7-9f61-d189021fb45e.png)

Which allow "modules" (or relationships between certain channels) to be registered.
![register](https://user-images.githubusercontent.com/6857168/127539060-a6356b23-5ac5-4df8-8218-afb8c3e412da.png)

**I see two potential solutions.** 
1. add .SD as a field inside nirs(i).probe (for example, nirs(i).probe.SD), or
2. Add all the fields of the .SD file into the nirs(i).probe. (the .SD fields are copied below). 

Option 1 seems like the simplest, most compatible option. It would allow AtlasViewer to export .SD files and easily append to snirf files. The downside if that you'll have multiple fields with different names but describing the same things (e.g. nirs(i).probe.SD.SrcPos and snirf(i).sourcePos2D define the same thing).
Option 2 would require AtlasViewer to export snirf files, with only the nirs(i).probe populated. 

Whoever option we choose, we also need to update the nirs2snirf converter. (For example, I am unable to load probes using PlotProbe in Homer 3 from snirf files that have been converted from nirs files with nirs.SD inside (likely because these .SD fields are not carried over). However, I'll post this issue in Homer3 repository to keep us organized. )

Thoughts?

**Comment by dboas** [comment]
@morrisvanegas , my lab is dealing with this issue too! Our solution is different and reflects the reality that SNIRF was designed for storing acquired data. For acquired data, the probe position is already designed and their is no need to preserve the spring list information. This is why SNIRF stores the 3D positions of the sources and detectors as well as the 3D positions of 10-20 reference landmarks, all in the same coordinate system, so that users know where on the head the optodes were located. SNIRF also allows for the storage of 2D positions of sources and detectors to make it easier to view optode arrangements in 2D space.

But, the community still will benefit from a file format that preserves the spring information so that we can impose rigid distances between optodes when we are designing a probe. For now, we still have the spring list in the SD file format for this purpose. 

As such, I am presently inclined to not promote adding this information to SNIRF.

BTW, Sreekanth Kura and I have been extending AtlasViewer to easily allow 3D design of optode arrays directly on the head. And we added SrcPos2D,  SrcPos3D, etc (for detector and dummies) to the SD file. AV will now also export the probe to a snirf file for those who want to not deal with an SD file. It is working well. It will propagate to the development branch later this week.

In regards to the issue you are having with nirs2snirf conversion working in Homer, can you post that issue in the openfnirs.org homer forum?

**Comment by fangq** [comment]
I concur with @dboas, closing this issue for now.
