### ISSUE TITLE
dataTypeIndex is defined ambiguously

### ISSUE THREAD

**Issue by MichaelUM** [fNIRS/snirf#87]
The dataTypeIndex is not clearly defined. In the [data format summary ](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#snirf-data-format-summary) it is defined as an \<i\> integer but in the text [description](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsidatajmeasurementlistkdatatypeindex) it states _Data-type specific parameter indices_ and _Note that the Time Domain and Diffuse Correlation Spectroscopy data types have two additional parameters and so the data type index must be a vector with 2 elements that index the additional parameters._
Also here the type needs to be changed from Type: integer to Type: numeric 1-D array.

**Comment by samuelpowell** [comment]
Following meeting of May 24 it was agreed that `dataTypeIndex` should be a scalar which is used as an index into all appropriate fields. Indeed, it appears that this was the original intent since fields such as `/nirs(i)/probe/timeDelays` state, for example, that the "indexing of this field is paired with the indexing of probe.timeDelayWidths".

The fix here is to rewrite the [description](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsidatajmeasurementlistkdatatypeindex) and check that all fields for which the same index might be used contain similar text to that above, or at least, nothing contradictory.

**Comment by HanBnrd** [comment]
Hi, do you mean its type should be changed to `[<i>,....]`, and it should be renamed to `dataTypeIndices`? And therefore the way it is used should change too, for example [here](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsidatajmeasurementlistkdetectormoduleindex):
> For example, if `measurementList5` is a structure with `sourceIndex=2`, `detectorIndex=3`, `wavelengthIndex=1`, `dataType=1`,                               ~`dataTypeIndex=1`~ **`dataTypeIndices=[1]`** would imply that the data in the 5th column of the `dataTimeSeries` variable was measured with source #2 and detector #3 at wavelength #1.

**Comment by HanBnrd** [comment]
Alright, thanks for the details @samuelpowell, I'll open a PR.
